import { useState } from "react";
import axios from "axios";
import Head from "next/head";
import { uploadSuccess } from "../redux/actions/carAction";
import { useDispatch } from "react-redux";

function AddCar() {
  // data value
  <Head>
    <title>Add Car</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>;

  const [file, setFile] = useState(null);
  const [FilePrev, setFilePrev] = useState(null);
  const [carName, setCarName] = useState("");
  const [category, setCategory] = useState("");
  const [price, setPrice] = useState(0);
  const [status, setStatus] = useState(false);
  const dispatch = useDispatch();

  const onChangePicture = (e) => {
    // mengecek adakah file apa tidak
    if (e.target.files[0]) {
      setFile(e.target.files[0]);
      console.log(file);
      const reader = new FileReader();
      reader.addEventListener("load", () => {
        setFilePrev(reader.result);
      });
    }
  };

  // fungsi menggiram gambar
  const postToApi = () => {
    let FormData = require("form-data");
    let data = new FormData();
    data.append("name", carName);
    data.append("category", category);
    data.append("price", price);
    data.append("status", status);
    data.append("image", file);

    axios
      .post("https://rent-cars-api.herokuapp.com/admin/car", data)
      .then((res) => console.log(res));

    dispatch(uploadSuccess());
  };

  return (
    <div className="bg-[#F1F3FF] h-screen w-full">
      <h1 className="font-bold text-3xl py-14">Add new car </h1>
      <div className="add-container w-full bg-white  flex items-start justify-start flex-col">
        <div className="flex w-full my-2 items-center mx-10">
          <label
            class="block w-1/12 text-gray-700 text-sm font-bold mb-2"
            for="username"
          >
            Name
          </label>

          <input
            className="border-2 w-1/6 py-1 mx-24 border-[#3c3c3c]"
            onChange={(e) => setCarName(e.target.value)}
          ></input>
        </div>
        <div className="flex w-full my-2 items-center mx-10">
          <label
            class="block w-1/12 text-gray-700 text-sm font-bold mb-2"
            for="username"
          >
            Harga
          </label>
          <input
            className="border-2 w-1/6 py-1 mx-24 border-[#3c3c3c]"
            onChange={(e) => setPrice(e.target.value)}
          ></input>
        </div>
        <div className="flex w-full my-2 items-center mx-10">
          <label
            class="block w-1/12 text-gray-700 text-sm font-bold mb-2"
            for="username"
          >
            Foto
          </label>
          <input
            className="border-0 w-1/6 py-1 mx-24 border-[#3c3c3c]"
            onChange={(e) => {
              onChangePicture(e);
            }}
            type="file"
          />
        </div>
        <div className="flex w-full my-2 items-center mx-10">
          <label
            class="block  w-1/12 text-gray-700 text-sm font-bold mb-2"
            for="username"
          >
            Category
          </label>
          <input
            placeholder="-"
            className="border-0 w-1/6 py-1 mx-24 border-[#3c3c3c]"
            onChange={(e) => setCategory(e.target.value)}
          ></input>
        </div>
        <div className="flex w-full my-2 items-center mx-10">
          <label
            class="block  w-1/12 text-gray-700 text-sm font-bold mb-2"
            for="username"
          >
            Start Rent
          </label>
          <input
            placeholder="-"
            className="border-0 w-1/6 py-1 mx-24 border-[#3c3c3c]"
            onChange={(e) => setCategory(e.target.value)}
          ></input>
        </div>
        <div className="flex w-full my-2 items-center mx-10">
          <label
            class="block  w-1/12 text-gray-700 text-sm font-bold mb-2"
            for="username"
          >
            Finish Rent
          </label>
          <input
            placeholder="-"
            className="border-0 w-1/6 py-1 mx-24 border-[#3c3c3c]"
            onChange={(e) => setCategory(e.target.value)}
          ></input>
        </div>
        <div className="flex w-full my-2 items-center mx-10">
          <label
            class="block  w-1/12 text-gray-700 text-sm font-bold mb-2"
            for="username"
          >
            Created at
          </label>
          <input
            placeholder="-"
            className="border-0 w-1/6 py-1 mx-24 border-[#3c3c3c]"
            onChange={(e) => setCategory(e.target.value)}
          ></input>
        </div>
        <div className="flex w-full my-2 items-center mx-10">
          <label
            class="block  w-1/12 text-gray-700 text-sm font-bold mb-2"
            for="username"
          >
            Updated at
          </label>
          <input
            placeholder="-"
            className="border-0 w-1/6 py-1 mx-24 border-[#3c3c3c]"
            onChange={(e) => setCategory(e.target.value)}
          ></input>
        </div>
        <div className="flex w-full my-2 items-center mx-10">
          <button className="border-2 border-[#3c3c3c]" onClick={postToApi}>
            Upload
          </button>
        </div>
      </div>
    </div>
  );
}

export default AddCar;
